knp_snappy:
    pdf:
        enabled:    true
        binary:     '/usr/local/bin/wkhtmltopdf'
        options:    
            no-outline : true
            page-size : A4
            encoding : UTF-8
            enable-local-file-access : true
        
    image:
        enabled:    true
        binary:     '/usr/local/bin/wkhtmltopdf'
        options:    []
